### PR TITLE
WIP: Add Leanpub preview/publish script 

### PR DESCRIPTION
**Pull request by cansavvy**
**These changes were originally started from this PR:** https://github.com/jhudsl/ITCR_Course_Template_Bookdown/pull/18

### Summary 

This is a first step toward: #11 
This script we can use to publish or preview items to Leanpub. I still need to add instructions for this on CONTRIBUTING.md. 

This would be the basic usage: 
```
Rscript scripts/preview-leanpub.R \
-s jhu/jhudsl_course_template \
-a <Whatever your API Key is here>
```
Or you can set your API key to the environment so leanpubr will grab it. 

Currently, I'm having troubles getting the preview to work -- I wonder if its because this will only work if the course is already published? Not sure.

### CODE REVIEW

**Comment by cansavvy** [comment]
I've temporarily made this git repository public just so that is one less variable to deal with.

**Comment by muschellij2** [comment]
It's unclear what the slug is in this case.  Like @carriewright11 said, it'd be something like:
https://leanpub.com/courses/jhu/cbds-chromebook/read/1

so is the slug: `courses/jhu/cbds-chromebook` or `jhu/cbds-chromebook` or `cbds-chromebook`.  I'd normally think just `jhu/cbds-chromebook` would make the most sense, but our book `biostatmethods` is just https://leanpub.com/biostatmethods.  So maybe trying those 3 cases would be helpful debugging.

**Comment by cansavvy** [comment]
All these slugs give the same result as above: 
- `jhu/jhudsl_course_template`
- `courses/jhu/jhudsl_course_template`
- `courses/jhudsl_course_template`

But, when I use `https://leanpub.com/jhudsl_course_template/preview.json` I still get an error, but it's a different error: `{"error": "not_found"}` Is this progress? I don't know.

**Comment by muschellij2** [comment]
When you say "I *use* https://..." - are you navigating that on a browser?  If so, that's because it's a GET request when navigating, but the endpoint is a POST, so that'd make sense

**Comment by cansavvy** [comment]
> When you say "I _use_ https://..." - are you navigating that on a browser? I

I meant that I'm using that in the command provided by Leanpub [as described above](https://github.com/jhudsl/ITCR_Course_Template_Leanpub/pull/10#issuecomment-818640973). So like this (but I actually use my API key): 
```
curl -d "api_key=YOUR_API_KEY" https://leanpub.com/jhudsl_course_template/preview.json
```

**Comment by carriewright11** [comment]
OK i got this to work for the tidyverse course like so:
curl -d "api_key=YOUR_API_KEY" https://leanpub.com/tidyverseskillsdatascience/preview.json

When I include 'jhu' in the path it does not work and I get the error that @cansavvy got.  The output was {"success":true} and I can see that it is very slowly trying to make a new preview when I check on leanpub. I tried the same thing four our template and got this: {"error": "not_found"}

**Comment by carriewright11** [comment]
I meant to say the tidyverse **book** not course (which is published) - just in case there are differences for courses and books.

**Comment by carriewright11** [comment]
I think we could maybe try publishing our template course (and unpublishing if we want) to test this (http://help.leanpub.com/en/articles/110680-can-i-unpublish-my-book-how)

**Comment by cansavvy** [comment]
@carriewright11 these tests are great! I think we're narrowing in on the issue! Publishing and unpublishing sounds good to me for a test.

**Comment by carriewright11** [comment]
Ok before we try to publish... 
I tried this and seems like I might be getting somewhere:
curl -d "api_key=YOUR_API_KEY" https://leanpub.com/course_admin/jhu/jhudsl_course_template/preview.json

**Comment by carriewright11** [comment]
It seems to redirect me to log in even though I am - so maybe someone else should try that last command.

**Comment by carriewright11** [comment]
also it could be because I am technically still working on another preview :P

**Comment by cansavvy** [comment]
> It seems to redirect me to log in even though I am - so maybe someone else should try that last command.

I am getting the same response (even though I am also logged in).

**Comment by carriewright11** [comment]
interesting... wonder why... thanks for checking!

**Comment by cansavvy** [comment]
This PR is outdated. Closing it.

**Pull request closed without merging**
