### PR TITLE
Some polishing of coursera quiz conversion

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?
The script for converting quizzes from leanpub ->  coursera didn't work for my quizzes, so I did some adjusting. This should be more broadly applicable (I think). It's been working so far. 

I will do more testing to make sure. This is something we could add to a potential CourseraBuild: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/166

#### What was your approach?
There are three functions: 

`find_end_of_prompt()`
`convert_quiz()`
`convert_coursera_quizzes()`

The main function `convert_coursera_quizzes()` takes an input and output directory to convert all quizzes. It calls `convert_quiz()` for each quiz. `find_end_of_prompt()` is called by `convert_quiz()` to find the end of the prompt. 

If you test this on an individual quiz, you can look at the `quiz_line_df` to see how the tagging of the line types works. Things are labeled as: "prompt", "extended_prompt", "wrong_answer", "correct_answer", "other", "tag", "empty".

Empty and tag lines are deleted. (But eventually we may want to do something with the tags, so I kept in these labels for now). 
prompt lines are used to find the "extended_prompts" it assumes everything between the beginning of the prompt and the first answer are a part of the prompt. 

The correct and wrong answer declarations are made to be more flexible. But this still only works for multiple choice (no short answers). 

"other" lines are removed at the very end since I'm not sure we need to keep them.

### CODE REVIEW

**Comment by cansavvy** [comment]
Some things are still *slightly* off, still doing some more polishing and troubleshooting.

**Comment by cansavvy** [comment]
Okay, @carriewright11 this is the output from this script. Can you let me know if it looks right as far as you know?

[leanpub_ready_quiz_ch6.md.yml.zip](https://github.com/jhudsl/DaSL_Course_Template_Leanpub/files/7131174/leanpub_ready_quiz_ch6.md.yml.zip)

**Comment by cansavvy** [comment]
Last thing I need to take care of that I lost here is the multiple correct answers: `Error in question starting on line 16 :  `.isCorrect` must be set `true` for exactly one option`

Previously the code got rid of the odd answers. I'll add that back.

**Comment by carriewright11** [comment]
> Okay, @carriewright11 this is the output from this script. Can you let me know if it looks right as far as you know?
> [leanpub_ready_quiz_ch6.md.yml.zip](https://github.com/jhudsl/DaSL_Course_Template_Leanpub/files/7131271/leanpub_ready_quiz_ch6.md.yml.zip)
> 
> Edit: Coursera is complaining about the ` - answer:` and I'm not sure why, your file has those but it worked for you?

looks like "options: isn't always there"

**Comment by carriewright11** [comment]
> Last thing I need to take care of that I lost here is the multiple correct answers: `Error in question starting on line 16 : `.isCorrect`must be set`true` for exactly one option`
> 
> Previously the code got rid of the odd answers. I'll add that back.

There was an updated version that got rid of all other correct answers except the first one

**Comment by cansavvy** [comment]
> > Okay, @carriewright11 this is the output from this script. Can you let me know if it looks right as far as you know?
> > [leanpub_ready_quiz_ch6.md.yml.zip](https://github.com/jhudsl/DaSL_Course_Template_Leanpub/files/7131271/leanpub_ready_quiz_ch6.md.yml.zip)
> > Edit: Coursera is complaining about the ` - answer:` and I'm not sure why, your file has those but it worked for you?
> 
> looks like "options: isn't always there"

I noticed that and it should be fixed.

**Comment by cansavvy** [comment]
> There was an updated version that got rid of all other correct answers except the first one

Oh so do I not need to accommodate for that then?

**Comment by carriewright11** [comment]
> > There was an updated version that got rid of all other correct answers except the first one
> 
> Oh so do I not need to accommodate for that then?

I mean I updated my script (got rid of all other correct answers if there are more than two instead of just odd correct answers) - still need to accommodate for that for coursera

**Comment by cansavvy** [comment]
Okay, I've incorporated the goal of #56 to drop all but the first correct answer. 

I ran this on the original quiz and it worked when I uploaded it to Coursera. 

Next up I need to try it on my Docs and Usability quizzes but before I do that I need to figure out how to add images.

**Comment by cansavvy** [comment]
I think I"m going to save doing the images for a separate PR. This feels like enough for now.

**Comment by cansavvy** [comment]
The issue #59 has been filed to keep track of that.

**Pull request merged**
